addon:
  options:
    message: '<%= m.addon.name %> files copied.'


vendor:
  options:
    message: Vendor files updated.


config:
  options:
    message: Config files copied.




notify_hooks:
  options:
    success: true
    title: '<%= m.addon.name %>'
