addon:
  files:
    - <%= m.addon.dir %>/*.{php,yaml,html}
  tasks:
    - copy:addon
    - notify:addon


vendor:
  files:
    - <%= m.addon.dir %>/vendor/**
  tasks:
    - copy:vendor
    - notify:vendor


# config:
#   files:
#     - _config/add-ons/<%= m.addon.dir %>/*.yaml
#   tasks:
#     - copy:config
#     - notify:config




configFiles:
  files:
    - Gruntfile.js
    - meerkat/**
